// Blog Posts Data — Betzalel Cohen "Betochami"
// Auto-extracted from betochami.blogspot.com

const POSTS = [
  // ===== 2026 =====
  { year: 2026, date: "2026-01-07", title: "חַיֵּי אָדָם הוּא דְּזָל", excerpt: "ביטוי תלמודי על חיי אדם שזולים — מבט על גישת החברה החרדית לערך חיי אדם, משירות צבאי דרך מירון ועד קורונה.", url: "https://betochami.blogspot.com/2026/01/blog-post.html" },

  // ===== 2025 =====
  { year: 2025, date: "2025-09-15", title: "הקונספציה של הפילנתרופיה בנוגע לקהילה החרדית", excerpt: "ביקורת על עקרונות הפילנתרופיה כלפי הקהילה החרדית — טיפול בהנהגה רבנית כשומרי סף, הימנעות מקונפליקט, העדפת מיינסטרים.", url: "https://betochami.blogspot.com/2025/09/blog-post.html" },
  { year: 2025, date: "2025-08-31", title: "המערה החרדית", excerpt: "הקבלה בין מערת אפלטון לסיפור רשב\"י — כיצד החברה החרדית חיה בבידוד ובניתוק מהמציאות החיצונית.", url: "https://betochami.blogspot.com/2025/08/blog-post.html" },
  { year: 2025, date: "2025-05-20", title: "עיתון חדש \"לכתחילה\"", excerpt: "השקת עיתון חרדי דיגיטלי חדש המשלב תורה עם חיים מעשיים — תקוות וחששות על בסיס ניסיון היסטורי.", url: "https://betochami.blogspot.com/2025/05/blog-post.html" },
  { year: 2025, date: "2025-01-26", title: "לאן נעלמה אהבת הדעת? טור כאוב על משבר החינוך", excerpt: "ביקורת מקיפה על איכות החינוך החרדי — ירידה באיכות המורים, מוטיבציה חלשה, הכשרה לא מספקת.", url: "https://betochami.blogspot.com/2025/01/blog-post.html" },

  // ===== 2024 =====
  { year: 2024, date: "2024-12-26", title: "ועל המלחמות — מחשבות על שירות חרדים בצה\"ל", excerpt: "דיון בגיוס חרדים ליחידת החשמונאים בחנוכה — על הפער בין חרדים שמרנים למודרניים בנושא השירות.", url: "https://betochami.blogspot.com/2024/12/blog-post.html" },
  { year: 2024, date: "2024-07-21", title: "לקראת 'שירות לכתחילה'", excerpt: "שישה עקרונות מנחים לשירות חרדי — התמקדות בקהילות מודרניות, הפסקת מימון, שירות לפני תמיכה ממשלתית.", url: "https://betochami.blogspot.com/2024/07/blog-post_21.html" },
  { year: 2024, date: "2024-07-15", title: "ישיבת 'תפארת בחורים'", excerpt: "הכרזה על הקמת ישיבת הסדר חרדית המשלבת לימוד תורה עם שירות צבאי.", url: "https://betochami.blogspot.com/2024/07/blog-post.html" },
  { year: 2024, date: "2024-02-05", title: "שינוי האקלים — על שירות חרדים בצה\"ל", excerpt: "ראיון במקור ראשון על שינוי האקלים בנושא שירות חרדי.", url: "https://betochami.blogspot.com/2024/02/blog-post.html" },

  // ===== 2023 =====
  { year: 2023, date: "2023-11-23", title: "גיוס חרדים כיצד?", excerpt: "ניתוח האם ייתכנו שינויים משמעותיים בדפוסי הגיוס של צעירים חרדים.", url: "https://betochami.blogspot.com/2023/11/blog-post.html" },
  { year: 2023, date: "2023-10-19", title: "נושא בעול עם חבירו", excerpt: "על אחריות קולקטיבית בזמן משבר לאומי — השתתפות הקהילה החרדית בסולידריות.", url: "https://betochami.blogspot.com/2023/10/blog-post_19.html" },
  { year: 2023, date: "2023-10-09", title: "מחשבות בעקבות המצב", excerpt: "הרהורים על משבר 7 באוקטובר — אחדות לאומית, קריסת מערכות ביטחון, חשיבות הדיאלוג.", url: "https://betochami.blogspot.com/2023/10/blog-post.html" },
  { year: 2023, date: "2023-09-06", title: "מה לנו נרדמים?", excerpt: "ניתוח הניתוק של הקהילה החרדית מהמהפכות החברתיות בישראל — שינויים דמוגרפיים ושחיקת קונסנזוס.", url: "https://betochami.blogspot.com/2023/09/blog-post.html" },
  { year: 2023, date: "2023-08-21", title: "למה החרדים אינם מתגייסים לצה\"ל?", excerpt: "שבע סיבות שונות לאי-גיוס — חששות תיאולוגיים, עלויות חברתיות ופחד מאבדן זהות.", url: "https://betochami.blogspot.com/2023/08/blog-post_21.html" },
  { year: 2023, date: "2023-08-01", title: "הציונות ומדינת ישראל — אתגר תאולוגי ואידאולוגי", excerpt: "מתחים בין ציונות, הקמת מדינה וציפיות גאולה יהודיות מסורתיות.", url: "https://betochami.blogspot.com/2023/08/blog-post.html" },
  { year: 2023, date: "2023-07-30", title: "לקראת שותפות חדשה", excerpt: "על קואליציות פוליטיות ומציאת שותפים אמיתיים לשלטון משותף.", url: "https://betochami.blogspot.com/2023/07/blog-post.html" },
  { year: 2023, date: "2023-06-19", title: "ויקהלו על משה ועל אהרן / יתד נאמן", excerpt: "מערכת ביקורתית מיתד נאמן נגד חזון החינוך של הרב דוד לייבל.", url: "https://betochami.blogspot.com/2023/06/blog-post_19.html" },
  { year: 2023, date: "2023-06-11", title: "חזון החינוך החרדי / הרב דוד לייבל", excerpt: "תמלול נאומו של הרב דוד לייבל בעד פלורליזם בחינוך החרדי — מודל 'גם וגם'.", url: "https://betochami.blogspot.com/2023/06/blog-post.html" },
  { year: 2023, date: "2023-05-17", title: "חינוך כהלכה", excerpt: "עשרה עקרונות יסוד למצוינות חינוכית — כוח אדם מקצועי, קבלה הוגנת, בטיחות, הוראה נכונה.", url: "https://betochami.blogspot.com/2023/05/blog-post.html" },
  { year: 2023, date: "2023-05-02", title: "אחים יקרים, לא זו הדרך", excerpt: "אזהרה מפני גישות כפייתיות לשינוי חברתי — קריאה לדיאלוג ושותפות עם בעלי עניין חרדים.", url: "https://betochami.blogspot.com/2023/05/blog-post_2.html" },
  { year: 2023, date: "2023-03-28", title: "גדול השלום", excerpt: "הרהורים על עשרים שנה של עבודה לדיאלוג בין מגזרים בחברה הישראלית.", url: "https://betochami.blogspot.com/2023/03/blog-post.html" },
  { year: 2023, date: "2023-02-28", title: "חרדים לדמוקרטיה", excerpt: "ניתוח סכנות הקואליציה והרפורמה המשפטית מנקודת מבט חרדית.", url: "https://betochami.blogspot.com/2023/02/blog-post_28.html" },
  { year: 2023, date: "2023-02-05", title: "כשהחרדים יהיו רוב / זווית קריאה", excerpt: "סקירת ספרו של איציק קרומבי 'כשהחרדים יהיו רוב' — ביקורת זהירה על האופטימיות.", url: "https://betochami.blogspot.com/2023/02/blog-post.html" },
  { year: 2023, date: "2023-01-31", title: "דור הפַּלָּגָה", excerpt: "סיפור מגדל בבל כמטאפורה לפיצול החברה הישראלית — אבדן 'שפה משותפת'.", url: "https://betochami.blogspot.com/2023/01/blog-post_31.html" },
  { year: 2023, date: "2023-01-10", title: "כוח המשיכה של הזרם המרכזי (המיינסטרים) החרדי", excerpt: "על כוח המשיכה של התרבות החרדית המרכזית והאתגרים ביוזמת שינויים.", url: "https://betochami.blogspot.com/2023/01/blog-post.html" },

  // ===== 2022 =====
  { year: 2022, date: "2022-11-09", title: "דאגה בלב איש — בעקבות תוצאות הבחירות לכנסת ה-25", excerpt: "הרהורים על הצלחת המפלגות החרדיות בבחירות — שמחה לצד דאגה על יחסי דתיים-חילוניים.", url: "https://betochami.blogspot.com/2022/11/blog-post.html" },
  { year: 2022, date: "2022-10-20", title: "תפארת בחורים כוחם", excerpt: "על תנועת 'תפארת בחורים' ההיסטורית ופוטנציאל התחדשותה לצעירים חרדים.", url: "https://betochami.blogspot.com/2022/10/blog-post.html" },
  { year: 2022, date: "2022-09-22", title: "בעיית ההתארגנות של החרדים המודרניים", excerpt: "למה חרדים מודרניים לא מצליחים להתאגד כוח פוליטי — שש מחסומים.", url: "https://betochami.blogspot.com/2022/09/blog-post_22.html" },
  { year: 2022, date: "2022-09-13", title: "\"מתווה בעלזא\" ולקחיו", excerpt: "על כישלון יוזמת המימון המוגבר לבתי ספר בעלזא תמורת לימודי ליבה.", url: "https://betochami.blogspot.com/2022/09/blog-post_13.html" },
  { year: 2022, date: "2022-09-07", title: "מדשתקי רבנן", excerpt: "דאגה מרדיקליזציה של צעירים חרדים ושתיקת המנהיגות הרבנית.", url: "https://betochami.blogspot.com/2022/09/blog-post.html" },
  { year: 2022, date: "2022-07-04", title: "קול קורא להקמת ישיבת 'עץ החיים'", excerpt: "קריאה להקמת ישיבה חדשה לתלמידים מצטיינים המבקשים עומק תורני ורוחב אינטלקטואלי.", url: "https://betochami.blogspot.com/2022/07/blog-post_4.html" },
  { year: 2022, date: "2022-07-04", title: "עץ חיים היא למחזיקים בה", excerpt: "הכרזה על הקמת ישיבת 'עץ חיים' — חזון וצוות מייסדים.", url: "https://betochami.blogspot.com/2022/07/blog-post.html" },
  { year: 2022, date: "2022-05-25", title: "מחשבות על התמסדות ועל אלימות", excerpt: "ניתוח מוסדיות ואלימות דרך הסכסוכים בחסידות גור.", url: "https://betochami.blogspot.com/2022/05/blog-post.html" },
  { year: 2022, date: "2022-03-23", title: "מחשבות על מנהיגות תורנית ו\"דעת תורה\"", excerpt: "על מושג 'דעת תורה' ואיך שחקנים פוליטיים משפיעים על ירושת מנהיגות רבנית.", url: "https://betochami.blogspot.com/2022/03/blog-post_23.html" },
  { year: 2022, date: "2022-03-21", title: "גלה כבוד מישראל", excerpt: "מחווה לרב חיים קנייבסקי לאחר פטירתו — מסירות לתורה ונגישות.", url: "https://betochami.blogspot.com/2022/03/blog-post.html" },
  { year: 2022, date: "2022-03-04", title: "די לחובבנות", excerpt: "ביקורת על הצעה חרדית להסמכה טיפולית אלטרנטיבית מחוץ למסגרות אקדמיות.", url: "https://betochami.blogspot.com/2022/03/blog-post_4.html" },
  { year: 2022, date: "2022-02-05", title: "לא רק ליב\"ה", excerpt: "לימודי ליבה הם רק חלק מהבעיה — צריך רפורמה חינוכית מקיפה.", url: "https://betochami.blogspot.com/2022/02/blog-post.html" },
  { year: 2022, date: "2022-01-17", title: "פרשת ולדר — מבט סוציולוגי", excerpt: "ניתוח סוציולוגי של תגובות הקהילה לפרשת חיים ולדר — הבדלים בין תת-קהילות חרדיות.", url: "https://betochami.blogspot.com/2022/01/blog-post.html" },

  // ===== 2021 =====
  { year: 2021, date: "2021-12-05", title: "אקשיבה — יד על הכתף", excerpt: "על פלטפורמת הייעוץ האנונימית לציבור החרדי — שאלות אמוניות ובעיות אישיות.", url: "https://betochami.blogspot.com/2021/12/blog-post.html" },
  { year: 2021, date: "2021-11-23", title: "יצירה חרדית — מה הבעיה?", excerpt: "על פער המגדר ביצירה התרבותית החרדית — נשים יוצרות בחופשיות, גברים נמנעים.", url: "https://betochami.blogspot.com/2021/11/blog-post_23.html" },
  { year: 2021, date: "2021-11-17", title: "הדרך למוגנות בקהילה החרדית", excerpt: "על מוגנות בקהילה החרדית בעקבות פרשת ולדר — פורסם בגלובס.", url: "https://betochami.blogspot.com/2021/11/blog-post.html" },
  { year: 2021, date: "2021-09-05", title: "אשת חיל מי ימצא", excerpt: "סקירת הסרט התיעודי 'אשת חיל' על אקטיביזם פוליטי של נשים חרדיות.", url: "https://betochami.blogspot.com/2021/09/blog-post_5.html" },
  { year: 2021, date: "2021-08-31", title: "הגיע זמן ממ\"ח", excerpt: "על חינוך ממלכתי-חרדי — מודל המשלב פיקוח ממלכתי עם אורח חיים חרדי.", url: "https://betochami.blogspot.com/2021/08/blog-post_31.html" },
  { year: 2021, date: "2021-08-25", title: "להקהל ולעמוד על נפשם", excerpt: "על קהילות חדשות לצעירים חרדים שאינם מרגישים בנוח בסביבה המסורתית.", url: "https://betochami.blogspot.com/2021/08/blog-post_25.html" },
  { year: 2021, date: "2021-08-23", title: "לאן הולכים מכאן?", excerpt: "הרהורים על הורדת גיל הפטור מגיוס ל-21 וההשלכות ארוכות הטווח.", url: "https://betochami.blogspot.com/2021/08/blog-post.html" },
  { year: 2021, date: "2021-06-10", title: "בנט ולפיד, למדו מטעותכם", excerpt: "קריאה לממשלת בנט-לפיד ללמוד מכישלונות העבר ביחסים עם הקהילה החרדית.", url: "https://betochami.blogspot.com/2021/06/blog-post.html" },
  { year: 2021, date: "2021-05-24", title: "בית יוצר לנשמת האומה", excerpt: "200 שנה לפטירת ר' חיים מוולוז'ין — על מהפכת הישיבה כמוסד עצמאי.", url: "https://betochami.blogspot.com/2021/05/blog-post_24.html" },
  { year: 2021, date: "2021-05-06", title: "דרך אכזריות — לעילוי נשמת הרוגי מירון", excerpt: "בעקבות אסון מירון — הרמב\"ם על אסונות שנגרמים בידי אדם וחובת החקירה.", url: "https://betochami.blogspot.com/2021/05/blog-post_6.html" },
  { year: 2021, date: "2021-05-03", title: "להקדים רפואה למכה", excerpt: "קריאה למעבר מצדקה ריאקטיבית למניעה פרואקטיבית — בריאות, בטיחות, חינוך.", url: "https://betochami.blogspot.com/2021/05/blog-post.html" },
  { year: 2021, date: "2021-04-14", title: "חשיבותה של אנחה", excerpt: "ביום הזיכרון — על הציפייה המינימלית שמנהיגים חרדים יביעו צער על אי-השתתפות בנטל.", url: "https://betochami.blogspot.com/2021/04/blog-post.html" },
  { year: 2021, date: "2021-03-18", title: "יָדֵינוּ לֹא שָׁפְכוּ אֶת הַדָּם הַזֶּה", excerpt: "על אחריות קהילתית להגנה על פגיעים — בעקבות פרשת ראש זק\"א.", url: "https://betochami.blogspot.com/2021/03/blog-post_18.html" },
  { year: 2021, date: "2021-03-15", title: "משבר והזדמנות", excerpt: "על יחסי חרדים-ישראלים בעקבות הקורונה — משבר אך גם הזדמנות לשינוי.", url: "https://betochami.blogspot.com/2021/03/blog-post.html" },
  { year: 2021, date: "2021-01-27", title: "ראיון בעיתון דה מרקר", excerpt: "ראיון בדה מרקר על החברה החרדית.", url: "https://betochami.blogspot.com/2021/01/blog-post_27.html" },
  { year: 2021, date: "2021-01-21", title: "אלמלא מוראה של מלכות", excerpt: "על השפעת מגפת הקורונה על המתח בין הקהילה החרדית לחברה הישראלית.", url: "https://betochami.blogspot.com/2021/01/blog-post_21.html" },
  { year: 2021, date: "2021-01-18", title: "חרדים, דתיים-לאומיים ומה שביניהם", excerpt: "על המפגשים בין בחורי ישיבות חרדיות ודתיות-לאומיות — דומים יותר משונים?", url: "https://betochami.blogspot.com/2021/01/blog-post_18.html" },
  { year: 2021, date: "2021-01-12", title: "מגפת הקורונה וחוק הגיוס", excerpt: "כיצד משבר הקורונה עשוי להשפיע על דיוני הגיוס העתידיים.", url: "https://betochami.blogspot.com/2021/01/blog-post.html" },

  // ===== 2020 =====
  { year: 2020, date: "2020-12-24", title: "הרהורים פוליטיים", excerpt: "ניתוח כישרונותיו של נתניהו לצד ביקורת על גישתו הפוליטית ופגיעה בחברה.", url: "https://betochami.blogspot.com/2020/12/blog-post_24.html" },
  { year: 2020, date: "2020-12-22", title: "פֶּן יִקְרָאֶנּוּ אָסוֹן", excerpt: "על הקריירה הפוליטית של בני גנץ ונטיית הבוחרים לחפש 'משיחים' חדשים.", url: "https://betochami.blogspot.com/2020/12/blog-post_22.html" },
  { year: 2020, date: "2020-12-10", title: "על הקִיקְיוֹנִיּוּת", excerpt: "ביקורת על מפלגות שצצות ונעלמות כקיקיון — פוגעות ביציבות הפוליטית.", url: "https://betochami.blogspot.com/2020/12/blog-post_10.html" },
  { year: 2020, date: "2020-12-07", title: "האם תיתכן 'חרדיות נטולת אידיאולוגיה'?", excerpt: "ניתוח מסגרות אידיאולוגיות מתפתחות בקהילות 'חרדים חדשים'.", url: "https://betochami.blogspot.com/2020/12/blog-post_7.html" },
  { year: 2020, date: "2020-12-07", title: "כוחם של רעיונות", excerpt: "40 שנה לפטירת הרב יצחק הוטנר — על שילוב מחשבה מיסטית בלימוד הישיבה.", url: "https://betochami.blogspot.com/2020/12/blog-post.html" },
  { year: 2020, date: "2020-11-30", title: "במסתרים תבכה נפשי", excerpt: "סקירת הסרט 'במסתרים' על חרדים ששומרים על מראה חיצוני דתי אך איבדו אמונה.", url: "https://betochami.blogspot.com/2020/11/blog-post_30.html" },
  { year: 2020, date: "2020-11-23", title: "להשפיע טוב בעולם", excerpt: "הרהורים על מורשתו של הרב ג'ונתן סאקס ותרומת היהדות לאנושות.", url: "https://betochami.blogspot.com/2020/11/blog-post_23.html" },
  { year: 2020, date: "2020-11-09", title: "בטל כבוד היהדות", excerpt: "הספד לרב ג'ונתן סאקס — קידוש השם דרך כתיבה והוראה.", url: "https://betochami.blogspot.com/2020/11/blog-post.html" },
  { year: 2020, date: "2020-11-02", title: "בין אידאות לפעולות", excerpt: "ביקורת על ההרצאה של מיכאל גודמן על ההבדלים בין חרדים לציונים.", url: "https://betochami.blogspot.com/2020/11/blog-post_2.html" },
  { year: 2020, date: "2020-10-31", title: "החרדים והסדר מדיני", excerpt: "ניתוח העמדות הפוליטיות המורכבות של הרב שך — שמאלני אידיאולוגית, ימני מעשית.", url: "https://betochami.blogspot.com/2020/10/blog-post_31.html" },
  { year: 2020, date: "2020-10-18", title: "שעת המבחן הגיעה", excerpt: "על חובת ציות לחוק בזמן הגבלות קורונה — ביקורת על ציות סלקטיבי.", url: "https://betochami.blogspot.com/2020/10/blog-post_18.html" },
  { year: 2020, date: "2020-10-14", title: "החרדים החדשים אַיְּכֵם?", excerpt: "אכזבה מהיעדרות 'החרדים החדשים' ממנהיגות קהילתית בתקופת הקורונה.", url: "https://betochami.blogspot.com/2020/10/blog-post_14.html" },
  { year: 2020, date: "2020-10-11", title: "אינטליגנציה חרדית", excerpt: "מחווה לפרופ' עמירם גונן — חזון של תלמידי חכמים משכילים.", url: "https://betochami.blogspot.com/2020/10/blog-post.html" },
  { year: 2020, date: "2020-10-04", title: "בין הבנה להכלה", excerpt: "ההבדל בין הבנת ההתנהגות החרדית להצדקתה — סובלנות אינה חוקיות.", url: "https://betochami.blogspot.com/2020/10/blog-post_4.html" },
  { year: 2020, date: "2020-09-24", title: "הכל בידי שמים חוץ מצינים פחים", excerpt: "נקודות מבט תיאולוגיות על הקורונה — הבדלים בין גישות ליטאיות לחסידיות.", url: "https://betochami.blogspot.com/2020/09/blog-post_24.html" },
  { year: 2020, date: "2020-09-14", title: "אנרכיה כאן ועכשיו", excerpt: "ביקורת על כישלון אכיפת החוק — 'אנרכיה בתוך אנרכיה'.", url: "https://betochami.blogspot.com/2020/09/blog-post_14.html" },
  { year: 2020, date: "2020-09-11", title: "המחיר הרוחני של נגיף הקורונה", excerpt: "ניתוח ההשפעה הרוחנית של הסגרים על קהילות חרדיות.", url: "https://betochami.blogspot.com/2020/09/blog-post_11.html" },
  { year: 2020, date: "2020-09-08", title: "פרשן ולא פרשן", excerpt: "סקירת ספרו של הרב אליעזר חיון על פרשנות מקראית.", url: "https://betochami.blogspot.com/2020/09/blog-post_8.html" },
  { year: 2020, date: "2020-09-03", title: "צעד ראשון בכיוון הנכון", excerpt: "על דרישת עופר שלח לבחירות דמוקרטיות בתוך יש עתיד.", url: "https://betochami.blogspot.com/2020/09/blog-post.html" },
  { year: 2020, date: "2020-08-31", title: "יחד שבטי ישראל", excerpt: "על הפרדה בחינוך החרדי — סוגיות חברתיות-כלכליות ואפליה.", url: "https://betochami.blogspot.com/2020/08/blog-post_31.html" },
  { year: 2020, date: "2020-08-26", title: "על גינונים ודיסטנס", excerpt: "בעקבות פטירת הרב שטיינזלץ, הרב גולדברג ופרופ' גביזון — על ענווה מול היררכיה.", url: "https://betochami.blogspot.com/2020/08/blog-post_26.html" },
  { year: 2020, date: "2020-08-18", title: "היהודים מוחים ומפגינים", excerpt: "ניתוח ההפגנות נגד 'היהודים באים' — האם המחאה משרתת את מטרותיה?", url: "https://betochami.blogspot.com/2020/08/blog-post.html" },

  // ===== 2019 =====
  { year: 2019, date: "2019-12-19", title: "מנהיגות רבנית לקהילות חרדיות מתחדשות", excerpt: "על הצורך הדחוף במנהיגות תורנית שתנחה קהילות חרדיות חדשות.", url: "https://betochami.blogspot.com/2019/12/blog-post_19.html" },
  { year: 2019, date: "2019-12-05", title: "מנהיגות רבנית לחרדיות המתחדשת", excerpt: "מיפוי מנהיגים תורניים פוטנציאליים לקהילות חרדיות מודרניות — דורות שונים.", url: "https://betochami.blogspot.com/2019/12/blog-post.html" },
  { year: 2019, date: "2019-11-21", title: "כחצים ביד גבור", excerpt: "על צרכי נוער חרדי מחוץ למסגרות ישיבתיות — צורך בתנועות נוער ומנטורים.", url: "https://betochami.blogspot.com/2019/11/blog-post_21.html" },
  { year: 2019, date: "2019-11-14", title: "לא מעבר לים", excerpt: "רשמים מביקור בישיבת אייזק אלחנן (ישיבה יוניברסיטי) — מודל 'דנים-אורתודוקס'.", url: "https://betochami.blogspot.com/2019/11/blog-post_16.html" },
  { year: 2019, date: "2019-11-07", title: "יפה תלמוד תורה עם דרך ארץ", excerpt: "על שילוב תורה וחיים מעשיים — רלוונטיות לחרדים ישראלים.", url: "https://betochami.blogspot.com/2019/11/blog-post.html" },
  { year: 2019, date: "2019-09-18", title: "שאלות דת ומדינה — פרשת דרכים", excerpt: "על מרכזיות נושאי דת ומדינה בפוליטיקה הישראלית.", url: "https://betochami.blogspot.com/2019/09/blog-post_18.html" },
  { year: 2019, date: "2019-09-15", title: "מפלגת 'כחול לבן' — אכזבה אישית", excerpt: "הרהורים על אכזבה ממפלגת כחול לבן ביחסה לנושאי דת ומדינה.", url: "https://betochami.blogspot.com/2019/09/blog-post_15.html" },
  { year: 2019, date: "2019-09-12", title: "מיפוי התקשורת החרדית", excerpt: "סקירת נוף המדיה החרדית — עיתונים, אתרים, פורומים ורדיו.", url: "https://betochami.blogspot.com/2019/09/blog-post_12.html" },
  { year: 2019, date: "2019-08-15", title: "שותפות קשה", excerpt: "ניתוח היחסים העמומים בין הקהילה החרדית למדינת ישראל.", url: "https://betochami.blogspot.com/2019/08/blog-post_15.html" },
  { year: 2019, date: "2019-08-06", title: "יהללך זר ולא פיך", excerpt: "הרהורים על שש שנים כמנהל ישיבת חכמי לב — הקמת כ-20 ישיבות תיכוניות חרדיות.", url: "https://betochami.blogspot.com/2019/08/blog-post.html" },
  { year: 2019, date: "2019-07-28", title: "חינוך לחדשנות טכנולוגית", excerpt: "על חינוך חרדים לשימוש אחראי באינטרנט וסמארטפונים.", url: "https://betochami.blogspot.com/2019/07/blog-post_28.html" },
  { year: 2019, date: "2019-07-23", title: "ראיתי עולם הפוך", excerpt: "על ההנגדה בין ישיבות דתיות-לאומיות (שתלמידיהן מתגייסים) לישיבות חרדיות.", url: "https://betochami.blogspot.com/2019/07/blog-post_23.html" },
  { year: 2019, date: "2019-07-11", title: "על הקונפורמיות", excerpt: "ביקורת על הדגש החרדי על אחידות בלבוש, אורח חיים וצריכה.", url: "https://betochami.blogspot.com/2019/07/blog-post_11.html" },
  { year: 2019, date: "2019-07-04", title: "אבני קודש תשתפכנה", excerpt: "ביקורת על ישיבות ענק (300+ תלמידים) על חשבון התפתחות אישית.", url: "https://betochami.blogspot.com/2019/07/blog-post.html" },
  { year: 2019, date: "2019-06-27", title: "הזכות למצוינות", excerpt: "על מריטוקרטיה בחינוך — סיפור קרח ומשמעותו.", url: "https://betochami.blogspot.com/2019/06/blog-post_30.html" },
  { year: 2019, date: "2019-06-20", title: "ועינינו לא ראו", excerpt: "על הימנעות התקשורת החרדית מלדווח על משברי בריאות נפשית והתאבדויות.", url: "https://betochami.blogspot.com/2019/06/blog-post_20.html" },
  { year: 2019, date: "2019-06-13", title: "להקדים רפואה למכה", excerpt: "על משבר הקבלה לבתי ספר — צורך בהערכת בתי ספר לפי איכות חינוכית.", url: "https://betochami.blogspot.com/2019/06/blog-post_13.html" },
  { year: 2019, date: "2019-06-10", title: "אקטיביזם בשביל מה?", excerpt: "הגנה על גישה אקטיביסטית לשינוי חברתי — מול גישה הדרגתית.", url: "https://betochami.blogspot.com/2019/06/blog-post_10.html" },

  // ===== 2018 =====
  { year: 2018, date: "2018-12-21", title: "אל תחטאו בילד", excerpt: "על שתי גישות לנוער בסיכון חרדי — ישיבות מיוחדות מול מסגרות צבאיות.", url: "https://betochami.blogspot.com/2018/12/blog-post_21.html" },
  { year: 2018, date: "2018-12-18", title: "תרבות של מחלוקת", excerpt: "על הצורך בכתב עת חרדי המאפשר דיאלוג פנימי מגוון.", url: "https://betochami.blogspot.com/2018/12/blog-post.html" },
  { year: 2018, date: "2018-11-21", title: "הליטאים החדשים", excerpt: "ניתוח ניצחון דגל התורה בבחירות ירושלים — מהנהגת הרב שך ל'חותמת גומי'.", url: "https://betochami.blogspot.com/2018/11/blog-post_21.html" },
  { year: 2018, date: "2018-11-11", title: "נוער בלי סיכוי", excerpt: "ביקורת על כנס נוער בסיכון — מטפלים בתסמינים ולא בסיבות.", url: "https://betochami.blogspot.com/2018/11/blog-post_11.html" },
  { year: 2018, date: "2018-11-06", title: "ודאשתמש בתגא חלף", excerpt: "על השימוש לרעה ב'דעת תורה' למטרות מסחריות ופוליטיות.", url: "https://betochami.blogspot.com/2018/11/blog-post_6.html" },
  { year: 2018, date: "2018-11-05", title: "אל הדגל", excerpt: "ניתוח כוחות בתוך דגל התורה לאחר פטירת הרב שטיינמן.", url: "https://betochami.blogspot.com/2018/11/blog-post.html" },
  { year: 2018, date: "2018-11-01", title: "עידן 'הטוב המשותף'", excerpt: "70 שנות מסלול חרדי — ממיעוט מאוים לעידן של שותפות.", url: "https://betochami.blogspot.com/2018/11/blog-post_1.html" },
  { year: 2018, date: "2018-10-30", title: "על פוליטיקה זהות והזדהות", excerpt: "למה מעורבות חרדית בפוליטיקה גבוהה מהאוכלוסייה הכללית.", url: "https://betochami.blogspot.com/2018/10/blog-post_30.html" },
  { year: 2018, date: "2018-10-27", title: "הרהורי טרום בחירות", excerpt: "ניתוח בשלוש רמות של בחירות מוניציפליות בירושלים.", url: "https://betochami.blogspot.com/2018/10/blog-post_27.html" },
  { year: 2018, date: "2018-10-19", title: "המפלגות החרדיות על פרשת דרכים", excerpt: "שלוש אפשרויות אסטרטגיות לחרדים לא מיוצגים.", url: "https://betochami.blogspot.com/2018/10/blog-post_19.html" },
  { year: 2018, date: "2018-09-26", title: "מפלגות גוליבר בארץ ליליפוט", excerpt: "ביקורת על מודל מפלגות מונהגות על ידי מנהיג אחד.", url: "https://betochami.blogspot.com/2018/09/blog-post_26.html" },
  { year: 2018, date: "2018-09-25", title: "תקופת הדמדומים של המפלגות החרדיות", excerpt: "תקופת ההיסטוריה הפוליטית החרדית — ועידן חדש מתהווה.", url: "https://betochami.blogspot.com/2018/09/blog-post_25.html" },
  { year: 2018, date: "2018-09-20", title: "קריאת כיוון למפלגות החרדיות", excerpt: "שלושה רפורמות מבניות למפלגות החרדיות.", url: "https://betochami.blogspot.com/2018/09/blog-post_20.html" },
  { year: 2018, date: "2018-09-08", title: "ירושלים שלי", excerpt: "הרהורים על ירושלים כעיר המאחדת שבטים — פלורליזם ודיאלוג.", url: "https://betochami.blogspot.com/2018/09/blog-post_8.html" },
  { year: 2018, date: "2018-09-05", title: "לתשובת השנה", excerpt: "על שתי גישות בעייתיות לתשובה — ודרך האמצע.", url: "https://betochami.blogspot.com/2018/09/blog-post.html" },
  { year: 2018, date: "2018-08-28", title: "עולם הישיבות הליטאי — מבט כללי", excerpt: "216 שנה מייסוד וולוז'ין — שלוש תקופות ותקופה רביעית מתהווה.", url: "https://betochami.blogspot.com/2018/08/blog-post_28.html" },
  { year: 2018, date: "2018-08-27", title: "שִׁבְתִּי בְּבֵית ה' כָּל יְמֵי חַיַּי", excerpt: "על חוויית ההתמסרות המוחלטת ללימוד תורה בישיבות הליטאיות.", url: "https://betochami.blogspot.com/2018/08/blog-post_27.html" },
  { year: 2018, date: "2018-08-22", title: "חינוך ל'תורה עם דרך ארץ' לכתחילה", excerpt: "על שילוב לימודי תורה ולימודים מעשיים מההתחלה — מודל חכמי לב.", url: "https://betochami.blogspot.com/2018/08/blog-post.html" },

  // ===== 2017 (selected) =====
  { year: 2017, date: "2017-12-24", title: "מי ומי ההולכים", excerpt: "על השקפת עולם רצויה ושותפים לגיטימיים — תורה ודרך ארץ כתחומים נפרדים.", url: "https://betochami.blogspot.com/2017/12/blog-post.html" },
  { year: 2017, date: "2017-12-04", title: "ועל הנדוניה", excerpt: "ניתוח מנהג הנדוניה בעולם הישיבות — הבדלים עדתיים ולחצים כלכליים.", url: "https://betochami.blogspot.com/2017/12/blog-post_4.html" },
  { year: 2017, date: "2017-11-25", title: "הדגלים הליטאיים", excerpt: "על הדגלים האידיאולוגיים של הקהילה הליטאית — עליונות התורה, מוסר, הלכה.", url: "https://betochami.blogspot.com/2017/11/blog-post.html" },
  { year: 2017, date: "2017-10-29", title: "מה רוצה 'הפלג הירושלמי'?", excerpt: "ניתוח המטרות האמיתיות של הפלג הירושלמי — מניעת מודרניזציה.", url: "https://betochami.blogspot.com/2017/10/blog-post_29.html" },
  { year: 2017, date: "2017-10-09", title: "סוגיית הכוללים", excerpt: "על מערכת הכוללים — קיימות כלכלית ואתגרים אישיים.", url: "https://betochami.blogspot.com/2017/10/blog-post_9.html" },
  { year: 2017, date: "2017-09-28", title: "תרבות חרדית וישראלית, הילכו יחדיו?", excerpt: "האם תרבות חרדית וישראלית יכולות לדור בכפיפה אחת?", url: "https://betochami.blogspot.com/2017/09/blog-post_28.html" },
  { year: 2017, date: "2017-09-12", title: "חינוך לאינטרנט ולסמארטפון", excerpt: "אינטרנט דורש חינוך, לא איסור — השוואה לרישיון נהיגה.", url: "https://betochami.blogspot.com/2017/09/blog-post.html" },
  { year: 2017, date: "2017-08-22", title: "כל ההתחלות קשות", excerpt: "על מעברים בין מוסדות חינוך — חשיבות החודש הראשון.", url: "https://betochami.blogspot.com/2017/08/blog-post_22.html" },
  { year: 2017, date: "2017-08-12", title: "קלקול השורה", excerpt: "ניתוח נייטרלי של נתניהו — אהבה ושנאה מעוותות שיפוט.", url: "https://betochami.blogspot.com/2017/08/blog-post.html" },
  { year: 2017, date: "2017-08-02", title: "הפחד מוצדק", excerpt: "הכרה בלגיטימיות החשש מפני מודרניזציה — תוך תמיכה ביוזמות חרדיות חדשות.", url: "https://betochami.blogspot.com/2017/08/blog-post_2.html" },
  { year: 2017, date: "2017-07-25", title: "לימוד גמרא כפתרון סודוקו", excerpt: "למה לימוד הגמרא מרתק — אתגר אינטלקטואלי מול יישום מעשי.", url: "https://betochami.blogspot.com/2017/07/blog-post_25.html" },
  { year: 2017, date: "2017-07-17", title: "בין בית שמאי ובית הלל לצדוקים ופרושים", excerpt: "הבחנה בין מחלוקת לגיטימית לדחייה מוחלטת בעולם החרדי.", url: "https://betochami.blogspot.com/2017/07/blog-post_17.html" },
  { year: 2017, date: "2017-07-10", title: "הר כגיגית", excerpt: "רשמים מביקור בבני ברק אחרי 20+ שנים — נוסטלגיה וביקורת.", url: "https://betochami.blogspot.com/2017/07/blog-post_10.html" },
  { year: 2017, date: "2017-07-03", title: "עולם בנוי חרב ובנוי", excerpt: "לזכר ארבעה מנהיגים גדולים שראו עולמות נחרבים ונבנו.", url: "https://betochami.blogspot.com/2017/07/blog-post.html" },
  { year: 2017, date: "2017-07-02", title: "מתווה הכותל ו'דעת תורה'", excerpt: "ניתוח שינוי העמדה הרבנית בנושא פשרת הכותל.", url: "https://betochami.blogspot.com/2017/07/blog-post_2.html" },
  { year: 2017, date: "2017-06-26", title: "האם ייפרדו דרכנו?", excerpt: "האם הסתעפות 'חרדים חדשים' מחייבת פיצול קהילתי?", url: "https://betochami.blogspot.com/2017/06/blog-post_26.html" },
  { year: 2017, date: "2017-06-23", title: "מורים תלמידים ובית הכנסת", excerpt: "על ההבדל בין מוסדות חינוך שהצוות מזדהה עם התלמידים לבין 'משימות הצלה'.", url: "https://betochami.blogspot.com/2017/06/blog-post_23.html" },

  // ===== 2016 (selected) =====
  { year: 2016, date: "2016-12-30", title: "כל הדרכים בחזקת סכנה", excerpt: "על המתח בין הנהגה חרדית שמתנגדת לאינטרנט ושירות צבאי — לבין מי שמתעלם מהאזהרות.", url: "https://betochami.blogspot.com/2016/12/blog-post_30.html" },
  { year: 2016, date: "2016-12-13", title: "ואתה תדבר אל כל חכמי לב", excerpt: "חנוכת בניין ישיבת חכמי לב — על המשימה והמחלוקת.", url: "https://betochami.blogspot.com/2016/12/blog-post_13.html" },
  { year: 2016, date: "2016-11-17", title: "מודלים של מנהיגות רוחנית", excerpt: "ניתוח שלושה ממדים של מנהיגות — החזון איש, הרב שך, הרב עובדיה.", url: "https://betochami.blogspot.com/2016/11/blog-post_17.html" },
  { year: 2016, date: "2016-11-07", title: "הקהילה החרדית הליטאית לְמִשְׁפְּחֹתֶיהָ", excerpt: "מיפוי תת-קבוצות בתוך הקהילה הליטאית — מיינסטרים, מודרניסטים, מפקפקים.", url: "https://betochami.blogspot.com/2016/11/blog-post.html" },
  { year: 2016, date: "2016-11-02", title: "הקהילה החרדית והפמיניזם", excerpt: "שינויים בחינוך ותעסוקה של נשים חרדיות — ללא מהפכה אידיאולוגית.", url: "https://betochami.blogspot.com/2016/11/blog-post_2.html" },
  { year: 2016, date: "2016-10-01", title: "האם הציבור הדתי והחרדי יכול להנהיג את המדינה?", excerpt: "האם הציבור הדתי-חרדי מבין ממשל מעבר להסדרי סטטוס קוו?", url: "https://betochami.blogspot.com/2016/10/blog-post.html" },
  { year: 2016, date: "2016-09-19", title: "אותו היום סלקוהו לשומר הפתח", excerpt: "על תהליכי קבלה לבתי ספר חרדיים — בית שמאי מול בית הלל.", url: "https://betochami.blogspot.com/2016/09/blog-post_19.html" },
  { year: 2016, date: "2016-09-07", title: "אתגרי החינוך החרדי", excerpt: "שלוש בעיות מרכזיות: קבלה סלקטיבית, היעדר לימודי ליבה, נשירה.", url: "https://betochami.blogspot.com/2016/09/blog-post.html" },
  { year: 2016, date: "2016-08-02", title: "הי חסיד, הי עניו — לזכר הרב יהודה עמיטל", excerpt: "מחווה לרב יהודה עמיטל — ענווה, מסירות לתלמידים, מוכנות לוותר.", url: "https://betochami.blogspot.com/2016/08/blog-post.html" },

  // ===== 2015 (selected) =====
  { year: 2015, date: "2015-12-26", title: "קדושית", excerpt: "על חזון עיר חרדית אידיאלית המשלבת תורה, חוכמה ואתיקה.", url: "https://betochami.blogspot.com/2015/12/blog-post_26.html" },
  { year: 2015, date: "2015-12-21", title: "הרהורים על הכלכלה החרדית", excerpt: "ניתוח כלכלי — מדדי תעסוקה מפספסים חלוקת עושר דרך נדל\"ן.", url: "https://betochami.blogspot.com/2015/12/blog-post_21.html" },
  { year: 2015, date: "2015-12-10", title: "מחשבות על פערי הדורות בקהילה החרדית", excerpt: "85% מהחרדים מתחת לגיל 40 — ההשלכות על מנהיגות ושינוי.", url: "https://betochami.blogspot.com/2015/12/blog-post_10.html" },
  { year: 2015, date: "2015-12-09", title: "אם אין אנו לנו, מי לנו?", excerpt: "על צמיחת מנהיגות חרדית אחראית מבפנים.", url: "https://betochami.blogspot.com/2015/12/blog-post_9.html" },
  { year: 2015, date: "2015-11-25", title: "החיילים החרדים הצילו את עולם התורה", excerpt: "הרב דוד בלוך: חיילים חרדים הפחיתו כעס ציבורי — הצילו מימון ישיבות.", url: "https://betochami.blogspot.com/2015/11/blog-post_25.html" },
  { year: 2015, date: "2015-11-09", title: "שותפות במשימת הביטחון ולא שוויון בנטל", excerpt: "מיסגור מחדש: לא 'שוויון בנטל' אלא 'שותפות במשימת הביטחון'.", url: "https://betochami.blogspot.com/2015/11/blog-post_9.html" },
  { year: 2015, date: "2015-11-06", title: "מיומנו של שד\"ר", excerpt: "יומן גיוס כספים לישיבת חכמי לב — אתגרים ופרספקטיבות שונות.", url: "https://betochami.blogspot.com/2015/11/blog-post_6.html" },
  { year: 2015, date: "2015-11-03", title: "עצמאות חינוכית", excerpt: "ביקורת על שליטה מופרזת של הממסד החרדי במוסדות חינוך.", url: "https://betochami.blogspot.com/2015/11/blog-post_3.html" },
  { year: 2015, date: "2015-11-02", title: "לשם מה לומדים גמרא?", excerpt: "על מטרת לימוד הגמרא — אימון בחשיבה תלמודית, לא רק ידע.", url: "https://betochami.blogspot.com/2015/11/blog-post_2.html" },
  { year: 2015, date: "2015-10-29", title: "המנהיג שלא שתק", excerpt: "לזכר הרב שך — מנהיגות שביטאה עמדות ברורות בכל סוגייה.", url: "https://betochami.blogspot.com/2015/10/blog-post_29.html" },

  // ===== 2014 =====
  { year: 2014, date: "2014-01-22", title: "הקהילה החרדית בישראל — בין אינטגרציה לסגרגציה", excerpt: "ניתוח מגמות סותרות: השתתפות גוברת בתעסוקה ואקדמיה לצד שמירה על הפרדה.", url: "https://betochami.blogspot.com/2014/01/blog-post.html" },

  // ===== 2012 =====
  { year: 2012, date: "2012-07-11", title: "של מי המדינה הזאת?", excerpt: "על אזרחות מול תושבות — היחס המורכב של החברה החרדית למדינה.", url: "https://betochami.blogspot.com/2012/07/blog-post.html" },
];
